// components/glossary.ts

const GLOSSARY_ZH: Record<string, string> = {
  '宏观经济': '指对整个经济体系的总量分析，包括国民收入、经济增长率、通货膨胀、失业率、利率等。',
  '产业链': '指从原材料采购、生产、加工、分销到最终消费者的整个链条，包括上游、中游和下游。',
  '基本面': '指对公司财务状况、盈利能力、管理水平、行业前景等内在价值的分析，是价值投资的基础。',
  '市场情绪': '指市场上投资者对未来价格走势的普遍心理预期，可以是乐观、悲观或中性。',
  '催化剂': '指可能引发资产价格大幅波动的特定事件或信息，如新产品发布、政策变化、并购等。',
  '投资逻辑': '指进行一项投资决策所依据的核心理由和分析框架。',
  '风险提示': '指投资中可能导致损失的各种不确定性因素的说明。',
  'a股': '指在中国内地注册、在上海或深圳证券交易所上市、以人民币计价和交易的普通股股票。',
  '港股': '指在香港联合交易所上市的股票。',
  '美股': '指在美国的证券交易所（如纽交所、纳斯达克）上市的股票。',
  'swot': '一种战略分析工具，用于评估一个组织的优势(Strengths)、劣势(Weaknesses)、机会(Opportunities)和威胁(Threats)。',
  'swot分析': '一种战略分析工具，用于评估一个组织的优势(Strengths)、劣势(Weaknesses)、机会(Opportunities)和威胁(Threats)。',
  'esg': '环境(Environmental)、社会(Social)和公司治理(Governance)的缩写，是衡量企业可持续性和社会责任的标准。',
  '市盈率': '也称为P/E ratio，是股票价格除以每股收益的比率，常用来评估股价水平是否合理。',
  '市净率': '也称为P/B ratio，是股票价格除以每股净资产的比率，用于衡量公司资产价值与市场价格的关系。',
  '毛利率': '指毛利润占销售收入的百分比，计算公式为：(销售收入 - 销售成本) / 销售收入。它反映了公司的初始盈利能力。',
  '净利率': '指净利润占销售收入的百分比，计算公式为：净利润 / 销售收入。它衡量公司最终的盈利能力。',
  '现金流': '指企业在一定会计期间内，通过经营、投资、筹资活动产生的现金流入和流出的总称。',
  '护城河': '指公司拥有的能够抵御竞争对手攻击的可持续竞争优势，由沃伦·巴菲特推广。',
  '蓝筹股': '指在所属行业内占有重要支配地位、业绩优良、成交活跃、红利优厚的大公司的股票。',
  '成长股': '指那些销售额和盈利增长速度高于市场平均水平的公司股票，通常市盈率较高。',
  '价值股': '指那些市场价格低于其内在价值（基本面）的股票，通常市盈率和市净率较低。',
  '量化交易': '利用计算机技术和数学模型去实现投资策略的过程，通过数据分析寻找投资机会。',
  '对冲基金': '采用各种交易策略（如多空仓、套利等）进行对冲、换位、套期、投机，以获取高额回报的投资基金。',
};

const GLOSSARY_EN: Record<string, string> = {
  'macroeconomy': 'Analysis of the economy as a whole, including national income, growth rate, inflation, unemployment, and interest rates.',
  'industry chain': 'The entire process from raw material procurement, production, processing, distribution to the final consumer, including upstream, midstream, and downstream.',
  'fundamentals': 'Analysis of a company\'s intrinsic value, including financial condition, profitability, management, and industry prospects. It is the basis of value investing.',
  'market sentiment': 'The general psychological expectation of investors about future price movements, which can be bullish, bearish, or neutral.',
  'catalyst': 'A specific event or information that may trigger a significant price movement in an asset, such as a new product launch, policy change, or merger.',
  'investment thesis': 'The core reasoning and analytical framework behind an investment decision.',
  'risk warning': 'A statement about the various uncertain factors in an investment that could lead to losses.',
  'a-share': 'Common stocks registered in mainland China, listed on the Shanghai or Shenzhen stock exchanges, and traded in RMB.',
  'hong kong stock': 'Stocks listed on the Hong Kong Stock Exchange.',
  'us stock': 'Stocks listed on stock exchanges in the United States, such as the NYSE or NASDAQ.',
  'swot': 'A strategic analysis tool used to assess an organization\'s Strengths, Weaknesses, Opportunities, and Threats.',
  'swot analysis': 'A strategic analysis tool used to assess an organization\'s Strengths, Weaknesses, Opportunities, and Threats.',
  'esg': 'Stands for Environmental, Social, and Governance, which are standards for measuring the sustainability and social responsibility of a company.',
  'p/e ratio': 'Also known as the Price-to-Earnings ratio, it is the ratio of a company\'s stock price to its earnings per share, often used to assess if a stock is overvalued or undervalued.',
  'p/b ratio': 'Also known as the Price-to-Book ratio, it is the ratio of a company\'s stock price to its book value per share, used to compare a company\'s market value to its book value.',
  'gross margin': 'The percentage of revenue that exceeds the cost of goods sold (COGS), calculated as: (Revenue - COGS) / Revenue. It reflects initial profitability.',
  'net margin': 'The percentage of revenue remaining after all operating expenses, interest, taxes, and preferred stock dividends have been deducted from a company\'s total revenue. It measures final profitability.',
  'cash flow': 'The total amount of money being transferred into and out of a business, especially as affecting liquidity, over a period of time.',
  'moat': 'A sustainable competitive advantage that a company has that protects it from competitors, a term popularized by Warren Buffett.',
  'blue-chip stock': 'Stock of a large, well-established, and financially sound company that has operated for many years.',
  'growth stock': 'A stock of a company that generates substantial and sustainable positive cash flow and whose revenues and earnings are expected to increase at a faster rate than the average company in the same industry.',
  'value stock': 'A stock that trades at a lower price compared to its fundamentals, such as earnings, sales, and book value.',
  'quantitative trading': 'A type of market strategy that uses mathematical models and computer algorithms to make trading decisions.',
  'hedge fund': 'A pooled investment fund that trades in relatively liquid assets and is able to make extensive use of more complex trading, portfolio-construction and risk management techniques to improve performance, such as short selling, leverage, and derivatives.',
};

export const GLOSSARIES = {
  zh: GLOSSARY_ZH,
  en: GLOSSARY_EN,
};
